#!/bin/bash
#
# Copyright (C) 2012 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
#
# This script is part of NethServer.
#
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
#
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#
INDEX_DIR='/'
JSON_DIR='/var/cache/duc'
DUC_DB=$JSON_DIR/duc.db
SIZE=10000000

# directory indexing
/usr/bin/duc index $INDEX_DIR -d $DUC_DB

# parse db into xml
/usr/bin/duc xml -s $SIZE -x -d $DUC_DB $INDEX_DIR > $JSON_DIR/tree.xml

# convert in file json and strip lines
/usr/share/duc/xml2json.py $JSON_DIR/tree.xml > $JSON_DIR/duc.json
